Added `Builder` class to build rules
chucker/PasswordRulesSharp pull request #8
Opened 2023-02-13 19:01 UTC by ricardoboss

Fixes #7

2023-02-13 20:04 UTC, chucker commented on PasswordRulesSharp.Tests/Builder/BuilderTests.cs
> +            .RequireAnyOf(CharacterClass.Lower, CharacterClass.Upper)
neat!

2023-02-13 20:05 UTC, chucker commented
I like it. Will have to play with it.

2023-02-13 20:10 UTC, ricardoboss commented
I played with the idea of refactoring `Rule` to `StringRule` or something like that, but it would break the existing API.

2023-02-13 20:27 UTC, chucker commented
> I played with the idea of refactoring `Rule` to `StringRule` or something like that, but it would break the existing API.

I'm OK with that, but I think I would prefer

* not having a `BaseRule`; call that `Rule`
* `Rule` (currently `BaseRule`)'s constructor being `internal`
* `Rule` having a static method `FromString`

2023-02-13 20:29 UTC, ricardoboss commented
When adding breaking changes, do you mind also refactoring all `Rule` classes into their own namespace (`PasswordSharpRules.Rules`)?

2023-02-13 20:31 UTC, chucker commented
> When adding breaking changes, do you mind also refactoring all `Rule` classes into their own namespace (`PasswordSharpRules.Rules`)?

Yeah, sounds good.

(`Tokenizer` should probably also be `internal`, and maybe move to a new namespace `PasswordSharpRules.Rules.Parsing`?)

2023-02-13 20:32 UTC, ricardoboss commented
I wouldn't want to touch the tokenizer, as it seems OOS for this PR

2023-02-13 20:52 UTC, chucker commented
> I wouldn't want to touch the tokenizer, as it seems out of scope for this PR

c9e3732c6af01c2618c9da7cd10c978fca26236a

2023-02-13 21:12 UTC, ricardoboss commented
@chucker Done

2023-02-13 21:14 UTC, ricardoboss commented
The only thing left that I would change is to make `IncompleteRule` internal too.

2023-02-14 17:11 UTC, chucker commented
> The only thing left that I would change is to make `IncompleteRule` internal too.

agreed

2023-02-14 17:53 UTC, chucker requested changes

2023-02-14 17:53 UTC, chucker commented on PasswordRulesSharp/Builder/Builder.cs
> +public class Builder
^

2023-02-14 17:56 UTC, ricardoboss commented on PasswordRulesSharp/Builder/Builder.cs
> +public class Builder
Yes.

2023-02-15 09:55 UTC, chucker approved these changes

2023-02-15 09:55 UTC, merged